# Site settings
title: DR. TIJO D - Production Engineering Researcher
email: tijodev@gmail.com
description: > # Minima uses this for SEO and the site footer
  Personal website and academic profile of Dr. Tijo D, specializing in Production Engineering, 
  Advanced Metal Joining, Non-Conventional Machining, and Surface Coatings.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Theme settings
theme: minima
plugins:
  - jekyll-feed

# Minima theme specific settings:

# Minima: Header and Social Links (These will appear in the main navigation bar)
header_pages:
  - index.md
  - publications.md
  - projects.md
  - references.md

minima:
  # Add your professional links here. They will appear as icons in the footer.
  social_links:
    linkedin: # ADD YOUR LINKEDIN PROFILE HANDLE HERE
    github: # ADD YOUR GITHUB USERNAME HERE
    # The email icon uses the 'email' defined above.
